# Apply Linux patches
# !!! Ubuntu patches are being applied with unattended-upgrades. This can be run ad-hoc if required !!!
#- hosts: all:!pve:!ansiblehosts
#  become: true
#  roles:
#    - apply_patches

# Reboot servers if required
#- hosts: all:!pve:!ansiblehosts
#  become: true
#  tasks:
#    - name: Unconditionally reboot the machine with all defaults
#      ansible.builtin.reboot:

# !!! pve hosts are excluded so they are patched sequentially (serial: 1) !!!
# !!! Controlling playbook execution: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_strategies.html !!!

# Apply Linux patches to Proxmox servers
- hosts: pve
  become: true
  serial: 1
  roles:
    - apply_patches    

# Configure Linux patches for Linux (Ubuntu) servers
- hosts: all:!pve
  become: true
  roles:
    - configure_patches