# Install Docker, initialize swarm and join mgrs and workers
- hosts: dockerhosts
  become: true
  roles:
    - docker_install

- name: Init Docker Swarm
  hosts: dockermgrs[0]
  become: true
  roles:
    - docker_swarm_init

- name: Join Managers
  hosts: dockermgrs
  become: true
  roles:
    - docker_swarm_join_mgr

- name: Join Workers
  hosts: dockerworkers
  become: true
  roles:
    - docker_swarm_join_worker