---
# K3s prerequisuites
- hosts: k3s
  become: true
  roles:
    - k3s_configure_prereq

# K3s HA Proxy LB
- hosts: k3slb
  become: true
  roles:
    - k3s_configure_haproxy

# Initialize K3s Control Plane
- hosts: k3ssvr[0]
  become: true
  roles:
    - k3s_initialize_control_plane
  vars_files:
    - roles/k3s_initialize_control_plane/vars/secrets.encrypted

# Join K3s Control Plane Servers
- hosts: k3ssvr[1:2]
  become: true
  roles:
    - k3s_initialize_join_svr
  vars_files:
    - roles/k3s_initialize_control_plane/vars/secrets.encrypted
# note: vars_files (encrypted secrets) are not stored in this role but in the role where the cluster is being initialized (k3s_initialize_control_plane).

# Join K3s Agent Nodes
- hosts: k3sagt
  become: true
  roles:
    - k3s_initialize_join_agt
  vars_files:
    - roles/k3s_initialize_control_plane/vars/secrets.encrypted    
# note: vars_files (encrypted secrets) are not stored in this role but in the role where the cluster is being initialized (k3s_initialize_control_plane).

# info: Configure K3s Manager

# Execute k3s_configure_mgr role on the K3s manager server (Install and configure kubectl,k9s)
- hosts: k3smgr
  become: true
  roles:
    - k3s_configure_mgr

# Check if k3s.yaml file exists on the K3s server and fetch it to the temporary location if it does not exist

# @high Should /tmp be changed to something else so the file is not lost after reboot and is only accessible by root?
# @low Can the checksum of the downloaded file be verified to ensure integrity?

- name: Check if /tmp/k3s.yaml exists on the K3s server
  tags: k3s,mgr
  hosts: k3ssvr[0]
  tasks:
  - name: Check if /tmp/k3s.yaml exists on the K3s server
    stat:
      path: /tmp/k3s.yaml
    register: k3syaml_stat
  become: true

- name: Fetch /etc/rancher/k3s/k3s.yaml from the K3s server to Temporary location
  hosts: k3ssvr[0]
  tasks:
    - name: Fetch file from source server
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /tmp/k3s.yaml
        flat: yes
      become: true
      when: k3syaml_stat.stat.exists == false

# Check if /home/k3s/.kube/config exists on the manager server, copy and rename it if it does not exist
- name: Check if /home/k3s/.kube/config exists on the manager server
  tags: k3s,mgr
  hosts: k3smgr 
  tasks:
  - name: Check if kubeconfig file exists
    stat:
      path: /home/k3s/.kube/config
    register: kubeconfig_stat
  become: true

- name: Copy file to destination server
  hosts: k3smgr
  tasks:
    - name: Copy k3s.yaml file to the manager server
      copy:
        src: /tmp/k3s.yaml
        dest: /home/k3s/.kube/config
        owner: k3s
        group: k3s
        mode: '0600'
      become: true
      when: kubeconfig_stat.stat.exists == false  

# Configure K3s Manager kubeconfig file
- name: Check if "/home/k3s/.kube/config" is already configured
  tags: k3s,lb
  hosts: k3smgr
  tasks:
    - name: Check if kubeconfig file exists
      command: 'grep "    server: https://127.0.0.1:6443" /home/k3s/.kube/config'
      register: kubeconfig_vip_check
      ignore_errors: true
      changed_when: false  # Ensure task is marked as "ok" instead of "changed" in the output
      failed_when: false  # Suppress output error if grep doesn't find a match

- name: Update /home/k3s/.kube/config LB address
  tags: k3s,lb
  hosts: k3smgr
  tasks:
    - name: Update LB address in kubeconfig
      lineinfile:
        path: /home/k3s/.kube/config
        regexp: "^    server"
        line: "    server: https://{{ lb_vip }}:6443"
      when: kubeconfig_vip_check.rc != 0 
  become: true          
