---

# info: Linux Baseline

# Apply base role
- hosts: all:!pve
  become: true
  roles:
    - base

# Install Software on Proxmox VMs
- hosts: all:!pve:!pi
  tags: apt
  become: true
  tasks:
  - name: Installing qemu-guest-agent on Ubuntu Proxmox VMs
    apt:
      name:
        - qemu-guest-agent
      state: latest

# info: Linux patching

# Apply Linux patches to Proxmox servers
- hosts: pve
  become: true
  serial: 1 # note: pve hosts are patched sequentially (serial: 1)
  roles:
    - apply_patches    
 
# Configure Linux patches for Linux (Ubuntu) servers
- hosts: all:!pve
  become: true
  roles:
    - configure_patches

# info: Role-Specific Playbooks

# Install Docker, initialize swarm and join mgrs and workers
# - import_playbook: configure_docker.yml

# Install K3s
- import_playbook: configure_k3s.yml

# todo: Ensure k3s user can run kubectl commands without sudo
# todo: Update k3s user's alias to type k instead of k3s kubectl
# todo: Install k9s on the manager node and make it available to k3s user
# todo: Install kubectl on the manager node and make it available to k3s user
# todo: Ensure kubectl can be run agains the VIP IP address from the manager node