# Apply base role
- hosts: all:!pve
  become: true
  roles:
    - base

# Apply Linux patches
- import_playbook: apply_linux_patches.yml

# Install Linux Software
- import_playbook: install_linux_software.yml

# Install Docker, initialize swarm and join mgrs and workers
- import_playbook: configure_docker.yml