# Apply base role

- hosts: all:!pve
  become: true
  roles:
    - base

# pve hosts are excluded so they are patched sequentially (serial: 1)
# Controlling playbook execution: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_strategies.html

- hosts: pve
  become: true
  serial: 1
  roles:
    - base    

# Install Software

- hosts: all:!pve:!pi
  become: true
  tasks:
  - name: Installing qemu-guest-agent on Ubuntu Proxmox VMs
    apt:
      name:
        - qemu-guest-agent
      state: latest

# Configure Docker

- hosts: dockerhosts
  become: true
  roles:
    - docker_install