- name: Install nfs-commons on Ubuntu servers
  tags: nfs,ubuntu   
  apt:
    name:
      - nfs-common
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install nfs-commons on Centos servers
  tags: nfs,centos   
  dnf:
    name:
      - nfs-common
    state: latest
  when: ansible_distribution == "CentOS"

- name: Mount an NFS volume
  tags: nfs
  mount:
    src: '{{ nfs_docker }}'
    path: /mnt/docker
    opts: rw,sync,hard
    state: mounted
    fstype: nfs

- name: Add User docker
  tags: docker
  user: 
    name: docker
    uid: 1005
    state: present      
    comment: "Add User docker"
    shell: /bin/bash

- name: Apply folder permissions for Docker mount
  file:
    path: /mnt/docker
    owner: docker
    group: docker

- name: Disable swap
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop: ["none", "swap"]    

# Install Docker on Ubuntu 24.04 LTS (Noble Numbat)

- name: Install required Docker system packages for Ubuntu
  tags: docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - virtualenv
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key for Ubuntu
  tags: docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Remove Docker Repository for 20.04 LTS (Focal Fossa)
  tags: docker
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: absent

- name: Add Docker Repository for 24.04 LTS (Noble Numbat)
  tags: docker
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu noble stable
    state: present    

- name: Update apt and install Docker packages on Ubuntu
  tags: docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    state: latest
    update_cache: true