# ------------------------------------------------------------
# NOTE: Servers
# ------------------------------------------------------------

# Servers Pihole
servers_pihole:
  hosts:
    srv-lxc-pihole[0:9]:

# Servers IaC
servers_iac:
  hosts:
    srv-lxc-iac[0:9]:    

# Servers Utility
servers_utility:
  hosts:
    srv-utl[0:9]:

# NOTE: Server Groups
servers:
  children:
    servers_pihole:
    servers_iac:
    servers_utility:

# NOTE: Proxmox servers

proxmox_vm:         # INFO: For installing qemu-guest-agent on Proxmox VM's (base | tasks | main | packages_base_qemu_agent.yml)
  children:
    servers_pihole:  # All Pihole servers 
    servers_utility: # All Utility Servers
    servers_iac:     # All IAC Servers    

# ------------------------------------------------------------
# NOTE: Workstations
# ------------------------------------------------------------

# Workstations General
workstations_general:
  hosts:
    ws-gen[0:9]:

# Workstations Development
workstations_dev:
  hosts:
    ws-dev[0:9]:
    

# NOTE: Workstation Groups
workstations:
  children:
    workstations_general:
    workstations_dev: