pi:
  hosts:
    pi1:
    pi2:
    pi3:
    pi4:

dockerhosts:
  hosts:
    pi1:
    pi2:
    pi3:
    pi4:

# Nested Groups

prod:
  children:
    pi:
    dockerhostsp:

staging:
  children:
    dockerhostss: