---
- name: Install FluxCD on K3s Manager
  shell: |
    curl -s https://fluxcd.io/install.sh | sudo bash
  become: true

- name: Copy Github SSH key for Flux
  copy:
    src: id_rsa_git_k8s
    dest: /home/k3s/.ssh/id_rsa_git_k8s
    owner: k3s
    group: k3s
    mode: 0600
  become: true

- name: Download SSH Config for Flux
  get_url:
    url: https://raw.githubusercontent.com/rtdevx/dotfiles/refs/heads/main/ssh/config_flux
    dest: /home/k3s/.ssh/config
    owner: k3s
    group: k3s    
    mode: '0600'

# note: FluxCD must be bootstrapped manually. There is an interactive prompt. Couldn't find anything in the documentation to automate this.

#- name: FluxCD Bootstrap GitHub
#  shell: |
#    flux bootstrap git \
#      --url=ssh://git@github.com/rtdevx/kubernetes.git \
#      --branch={{ flux_git_branch }} \
#      --private-key-file=/home/k3s/.ssh/id_rsa_git_k8s \
#      --password={{ id_rsa_git_k8s_passphrase }} \
#      --path=clusters/{{ flux_git_repo }}
#  become: true 