# Proxmox
pve:
  hosts:
    pve1:
    pve2:
    pve3:    

# Raspberry Pi
pi:
  hosts:
    pi1:
    pi2:
    pi3:
    pi4:

# Docker
dockerhosts:
  children:
    pi:
  hosts:
    swr-mgrp1:
    swr-nodep1:
    swr-nodep2:
  vars:
    nfs_docker: 192.168.20.5:/NFS/dockerp