# Proxmox
pve:
  hosts:
    pve1:
    pve2:
    pve3:

# Ansible hosts
ansiblehosts:
  hosts:
    ux-anss1: # info: Prod Ansible Control Node is running playbooks against Staging Ansible Control Node and vice versa.
      ansible_host:

# Raspberry Pi
pi:
  hosts:
    pi1:
    pi2:
    pi3:
    pi4:

# optimize: Variables are being duplicated here. Should be moved to a group_vars in the future. May affect "k3s_initialize_control_plane_join" role.

# K3s
k3smgr:
  hosts:
    k3s-mgrp1:
      ansible_host: 192.168.20.40
      lb_vip: 192.168.20.30
      flux_git_branch: main # note: FluxCD must be bootstrapped manually.
      flux_git_repo: production # note: FluxCD must be bootstrapped manually.

k3slb:
  hosts:
    k3s-lbp1:
      lb_state: MASTER
      lb_priority: 200      
      lb_vip: 192.168.20.30
      lb_url: k3s-vipp
      lb_url_fqdn: k3s-vipp.skynetx.uk                     
    k3s-lbp2:
      lb_state: BACKUP
      lb_priority: 100      
      lb_vip: 192.168.20.30
      lb_url: k3s-vipp
      lb_url_fqdn: k3s-vipp.skynetx.uk            

k3ssvr:
  hosts:
    k3s-srvp1:
      ansible_host: 192.168.20.41
      lb_vip: 192.168.20.30
      lb_url: k3s-vipp
      lb_url_fqdn: k3s-vipp.skynetx.uk     
# note: Uncomment the following lines if you have more servers in the k3s cluster.             
#    k3s-srvp2:
#      ansible_host: 192.168.20.42
#      lb_vip: 192.168.20.30
#      lb_url: k3s-vipp
#      lb_url_fqdn: k3s-vipp.skynetx.uk       
#    k3s-srvp3:
#      ansible_host: 192.168.20.43
#      lb_vip: 192.168.20.30
#      lb_url: k3s-vipp
#      lb_url_fqdn: k3s-vipp.skynetx.uk                   

k3sagt:
  hosts:
    k3s-agtp1:
      ansible_host: 192.168.20.45
    k3s-agtp2:
      ansible_host: 192.168.20.46

k3s:
  children:
    k3smgr:
    k3slb:     
    k3ssvr:
    k3sagt:   

# Docker
#dockermgrs:
#  hosts:
#    swr-mgrp1:
#      ansible_host: 192.168.20.91 #Hosts are in DNS. IP address only required for Docker Swarm Init (role: docker_swarm_init).

#dockerworkers:
#  hosts:
#    swr-nodep1:
#      ansible_host: 192.168.20.94 #Hosts are in DNS. IP address only required for Docker Swarm Init (role: docker_swarm_init).
#    swr-nodep2:
#      ansible_host: 192.168.20.95 #Hosts are in DNS. IP address only required for Docker Swarm Init (role: docker_swarm_init).

#dockerhosts:
#  children:
#    dockermgrs:
#    dockerworkers:
#  vars:
#    nfs_docker: 192.168.20.5:/NFS/dockerp