# Proxmox
pve:
  hosts:

# Ansible hosts
ansiblehosts:
  hosts:
    ux-anss1:

# Raspberry Pi
pi:
  hosts:

# K3s
k3smgr:
  hosts:
    k3s-mgrs1:
      ansible_host: 192.168.20.50

k3ssvr:
  hosts:
    k3s-srvs1:
      ansible_host: 192.168.20.51
    k3s-srvs2:
      ansible_host: 192.168.20.52
    k3s-srvs3:
      ansible_host: 192.168.20.53            

k3sagt:
  hosts:
    k3s-agts1:
      ansible_host: 192.168.20.55
    k3s-agts2:
      ansible_host: 192.168.20.56

k3s:
  children:
    k3smgr:
    k3ssvr:
    k3sagt:

# Docker
dockermgrs:
  hosts:
    swr-mgrs1:
      ansible_host: 192.168.20.37 #Hosts are in DNS. IP address only required for Docker Swarm Init (role: docker_swarm_init).

dockerworkers:
  hosts:
    swr-nodes1:
      ansible_host: 192.168.20.38 #Hosts are in DNS. IP address only required for Docker Swarm Init (role: docker_swarm_init).
    swr-nodes2:
      ansible_host: 192.168.20.39 #Hosts are in DNS. IP address only required for Docker Swarm Init (role: docker_swarm_init).

dockerhosts:
  children:
    dockermgrs:
    dockerworkers:
  vars:
    nfs_docker: 192.168.20.5:/NFS/dockers