# Proxmox
pve:
  hosts:

# Ansible hosts
ansiblehosts:
  hosts:
    ux-ansp1: # info: Prod Ansible Control Node is running playbooks against Staging Ansible Control Node and vice versa.

# Raspberry Pi
pi:
  hosts:

# optimize: Variables are being duplicated here. Should be moved to a group_vars in the future. May affect "k3s_initialize_control_plane_join" role.

# K3s
k3smgr:
  hosts:
    k3s-mgrs1:
      ansible_host: 192.168.20.50
      lb_vip: 192.168.20.39
      flux_git_branch: staging # note: FluxCD must be bootstrapped manually.
      flux_git_repo: staging # note: FluxCD must be bootstrapped manually.

k3slb:
  hosts:
    k3s-lbs1:
      lb_state: MASTER
      lb_priority: 200
      lb_vip: 192.168.20.39
      lb_url: k3s-vips
      lb_url_fqdn: k3s-vips.skynetx.uk      
    k3s-lbs2:
      lb_state: BACKUP
      lb_priority: 100      
      lb_vip: 192.168.20.39
      lb_url: k3s-vips
      lb_url_fqdn: k3s-vips.skynetx.uk

k3ssvr:
  hosts:
    k3s-srvs1:
      ansible_host: 192.168.20.51
      lb_vip: 192.168.20.39
      lb_url: k3s-vips
      lb_url_fqdn: k3s-vips.skynetx.uk    
# note: Uncomment the following lines if you have more servers in the k3s cluster.
#    k3s-srvs2:
#      ansible_host: 192.168.20.52
#      lb_vip: 192.168.20.39
#      lb_url: k3s-vips
#      lb_url_fqdn: k3s-vips.skynetx.uk      
#    k3s-srvs3:
#      ansible_host: 192.168.20.53
#      lb_vip: 192.168.20.39
#      lb_url: k3s-vips
#      lb_url_fqdn: k3s-vips.skynetx.uk                  

k3sagt:
  hosts:
    k3s-agts1:
      ansible_host: 192.168.20.55
    k3s-agts2:
      ansible_host: 192.168.20.56

k3s:
  children:
    k3smgr:
    k3slb:
    k3ssvr:
    k3sagt:

#Linux Test Servers
#linuxtest:
#  hosts:
#    ux-test1:
#      ansible_host: 192.168.20.241
#    ux-test2:
#      ansible_host: 192.168.20.242

# Docker
#dockermgrs:
#  hosts:
#    swr-mgrs1:
#      ansible_host: 192.168.20.97 #Hosts are in DNS. IP address only required for Docker Swarm Init (role: docker_swarm_init).

#dockerworkers:
#  hosts:
#    swr-nodes1:
#      ansible_host: 192.168.20.98 #Hosts are in DNS. IP address only required for Docker Swarm Init (role: docker_swarm_init).
#    swr-nodes2:
#      ansible_host: 192.168.20.99 #Hosts are in DNS. IP address only required for Docker Swarm Init (role: docker_swarm_init).

#dockerhosts:
#  children:
#    dockermgrs:
#    dockerworkers:
#  vars:
#    nfs_docker: 192.168.20.5:/NFS/dockers