# Proxmox
pve:
  hosts:

# Ansible hosts
ansiblehosts:
  hosts:
    ux-anss1:

# Raspberry Pi
pi:
  hosts:

# K3s
k3smgr:
  hosts:
    k3s-mgrs1:
      ansible_host: 192.168.20.50

k3scpl:
  hosts:
    k3s-cpls1:
      ansible_host: 192.168.20.51

k3swrk:
  hosts:
    k3s-wrks1:
      ansible_host: 192.168.20.55
    k3s-wrks2:
      ansible_host: 192.168.20.56

k3s:
  children:
    k3smgr:
    k3scpl:
    k3swrk:

# Docker
dockermgrs:
  hosts:
    swr-mgrs1:
      ansible_host: 192.168.20.37 #Hosts are in DNS. IP address only required for Docker Swarm Init (role: docker_swarm_init).

dockerworkers:
  hosts:
    swr-nodes1:
      ansible_host: 192.168.20.38 #Hosts are in DNS. IP address only required for Docker Swarm Init (role: docker_swarm_init).
    swr-nodes2:
      ansible_host: 192.168.20.39 #Hosts are in DNS. IP address only required for Docker Swarm Init (role: docker_swarm_init).

dockerhosts:
  children:
    dockermgrs:
    dockerworkers:
  vars:
    nfs_docker: 192.168.20.5:/NFS/dockers