# Proxmox
pve:
  hosts:

# Raspberry Pi
pi:
  hosts:

# Docker
dockermgrs:
  hosts:
    swr-mgrs1:
      ansible_host: 192.168.20.37 #Hosts are in DNS. IP address only required for Docker Swarm Init (role: docker_swarm_init).

dockerworkers:
  hosts:
    swr-nodes1:
      ansible_host: 192.168.20.38 #Hosts are in DNS. IP address only required for Docker Swarm Init (role: docker_swarm_init).
    swr-nodes2:
      ansible_host: 192.168.20.39 #Hosts are in DNS. IP address only required for Docker Swarm Init (role: docker_swarm_init).

dockerhosts:
  children:
    dockermgrs:
    dockerworkers:
  vars:
    nfs_docker: 192.168.20.5:/NFS/dockers