---
# Centos
- name: Install updates (CentOS)
  tags: always
  dnf:
    update_only: yes
    update_cache: yes
  when: ansible_distribution == "CentOS"
  register: updated
  notify: 
    - Reboot after update

# Ubuntu
- name: Install updates (Ubuntu)
  tags: always
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  register: updated
  notify: 
    - Reboot after update

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Remove dependencies that are no longer required and purge their configuration files
  apt:
    autoremove: yes
    purge: true

- name: Run the equivalent of "apt-get clean" as a separate step
  apt:
    clean: yes

#Debian
- name: Install updates (Debian)
  tags: always
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_distribution == "Debian"
  register: updated
  notify: 
    - Reboot after update