# INFO: Combined inventory file — hosts + constructed grouping
plugin: constructed

# INFO: Allow hosts that do not match any rule without failing
strict: false

# INFO: Define dynamic groups based on hostname patterns
groups:

  # INFO: Base classification
  servers: "'srv-' in inventory_hostname"
  desktops: "'ws-' in inventory_hostname"

  # INFO: Server categories
  server_iac: "'srv-iac' in inventory_hostname"
  server_swarm_manager: "'srv-docker-mgr' in inventory_hostname"
  server_swarm_host: "'srv-docker-host' in inventory_hostname"
  server_utility: "'srv-utl' in inventory_hostname"

  # INFO: Desktop categories
  desktop_general: "'ws-gen' in inventory_hostname"
  desktop_development: "'ws-dev' in inventory_hostname"

  # INFO: Region detection (p = prod, s = stg)
  prod: "inventory_hostname[-2] == 'p'"
  stg: "inventory_hostname[-2] == 's'"

# INFO: Define hosts for classification (explicit host list)
hosts:
  srv-iacs1:
  srv-iacp1:
  srv-utls1:
  srv-utlp1:
  srv-docker-mgrp1:
  srv-docker-hostp1:
  srv-docker-mgrs1:
  srv-docker-hosts1:
  ws-gens1:
  ws-genp1:
  ws-devs1:
  ws-devp1: