# INFO: Static inventory — explicit groups and hosts
all:
  children:
  
    # INFO: Servers group
    servers:
      hosts:
        srv-iacs1: {}
        srv-iacp1: {}
        srv-utls1: {}
        srv-utlp1: {}
        srv-docker-mgrs1: {}
        srv-docker-mgrp1: {}
        srv-docker-hosts1: {}
        srv-docker-hostp1: {}

    # INFO: Workstations group
    desktops:
      hosts:
        ws-gens1: {}
        ws-genp1: {}
        ws-devs1: {}
        ws-devp1: {}

    # INFO: Category groups (subset of servers/desktops)
    server_iac:
      hosts:
        srv-iacs1: {}
        srv-iacp1: {}

    server_swarm_manager:
      hosts:
        srv-docker-mgrs1: {}
        srv-docker-mgrp1: {}

    server_swarm_host:
      hosts:
        srv-docker-hosts1: {}
        srv-docker-hostp1: {}

    server_utility:
      hosts:
        srv-utls1: {}
        srv-utlp1: {}

    desktop_general:
      hosts:
        ws-gens1: {}
        ws-genp1: {}

    desktop_development:
      hosts:
        ws-devs1: {}
        ws-devp1: {}

    # INFO: Region groups (explicit)
    prod:
      hosts:
        srv-iacp1: {}
        srv-utlp1: {}
        srv-docker-mgrp1: {}
        srv-docker-hostp1: {}
        ws-genp1: {}
        ws-devp1: {}

    stg:
      hosts:
        srv-iacs1: {}
        srv-utls1: {}
        srv-docker-mgrs1: {}
        srv-docker-hosts1: {}
        ws-gens1: {}
        ws-devs1: {}