---
# Add user ansible
- name: Add User ansible
  tags: always
  user: 
    name: ansible
    #uid: 1001
    state: present
    groups: sudo
    comment: "Add User ansible"
    shell: /bin/bash

- name: Update authorized_keys for user ansible
  tags: always
  authorized_key:
    user: ansible
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPXFX63LfEGDYBI+bT1VeaTE/L+ovz8aPvl3nTk8vcSY ansible"

- name: Add sudoers file for ansible user
  tags: always
  copy:
    src: sudoer_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

# Add user robk
- name: Add User robk
  tags: always
  user: 
    name: robk
    uid: 1001
    state: present
    groups: sudo
    comment: "Add User robk"
    shell: /bin/bash

- name: Update authorized_keys for user robk
  tags: always
  authorized_key:
    user: robk
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOn55Ck/aZ/UdRTpw1DN9iGNBIksbvwjBGWWkdQ2QzRl robk"

- name: Add sudoers file for robk user
  tags: always
  copy:
    src: sudoer_robk
    dest: /etc/sudoers.d/robk
    owner: root
    group: root
    mode: 0440

# Install Software
- name: Installing Default software on All Debian and Ubuntu hosts
  tags: always,apt
  apt:
    name:
      - fail2ban
      - fontconfig # note: required for task: configure_linux_terminal.yml
      - tree
    state: latest

# info: Configure Starship prompt

# Configure Terminal for Linux hosts
- import_tasks: configure_linux_terminal.yml
#  when: inventory_hostname in groups['linuxtest']