- name: Install nfs-commons on Ubuntu Docker servers.
  tags: nfs,ubuntu   
  apt:
    name:
      - nfs-common
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install nfs-commons on Centos Docker servers.
  tags: nfs,centos   
  dnf:
    name:
      - nfs-common
    state: latest
  when: ansible_distribution == "CentOS"