# Install haproxy and keepalived
- name: Install haproxy and keepalived
  tags: k3s
  apt:
    name:
      - haproxy
      - keepalived
    state: latest
    update_cache: true

# Configure keepalived
## Check if config file is already configured and has the right values
- name: Check if 'lb_state' is already configured
  command: grep '    state {{ lb_state }}' /etc/keepalived/keepalived.conf
  register: lb_state_check
  ignore_errors: yes
  changed_when: false  # Ensures task is marked as "ok" instead of "changed"
  
- name: Check if 'lb_priority' is already configured
  command: grep '    priority {{ lb_priority }}' /etc/keepalived/keepalived.conf
  register: lb_priority_check
  ignore_errors: yes
  changed_when: false  # Ensures task is marked as "ok" instead of "changed"

- name: Check if 'lb_vip' is already configured
  command: grep '        {{ lb_vip }}' /etc/keepalived/keepalived.conf
  register: lb_vip_check
  ignore_errors: yes
  changed_when: false  # Ensures task is marked as "ok" instead of "changed"

## Configure keepalived if above conditions are not met
- name: Configure keepalived
  tags: k3s
  copy:
    src: keepalived.conf
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0440
  when: 
    - lb_state_check.rc != 0 # Only execute if grep didn't find a match
    - lb_priority_check.rc != 0  # Only execute if grep didn't find a match
    - lb_vip_check != 0  # Only execute if grep didn't find a match    

- name: Update keepalived state
  tags: k3s
  lineinfile:
    path: /etc/keepalived/keepalived.conf
    regexp: '^    state'
    line: '    state {{ lb_state }}'
  notify: Restart keepalived
  when: lb_state_check.rc != 0  # Only execute if grep didn't find a match    

- name: Update keepalived priority
  tags: k3s
  lineinfile:
    path: /etc/keepalived/keepalived.conf
    regexp: '^    priority'
    line: '    priority {{ lb_priority }}'
  notify: Restart keepalived
  when: lb_priority_check.rc != 0  # Only execute if grep didn't find a match    

- name: Update keepalived vip
  tags: k3s
  lineinfile:
    path: /etc/keepalived/keepalived.conf
    regexp: '^        lb_vip'
    line: '        {{ lb_vip }}/23'
  notify: Restart keepalived
  when: lb_vip_check.rc != 0  # Only execute if grep didn't find a match    

# Configure haproxy
## Check if config file is already configured and has the right values
- name: Check if 'haproxy control-plane-1' is already configured
  command: grep '    server control-plane-1 {{ hostvars[groups['k3ssvr'][0]].ansible_host }}:6443 check' /etc/haproxy/haproxy.cfg
  register: haproxy_cpl1_check
  ignore_errors: yes
  changed_when: false  # Ensures task is marked as "ok" instead of "changed"

- name: Check if 'haproxy control-plane-2' is already configured
  command: grep '    server control-plane-2 {{ hostvars[groups['k3ssvr'][1]].ansible_host }}:6443 check' /etc/haproxy/haproxy.cfg
  register: haproxy_cpl2_check
  ignore_errors: yes
  changed_when: false  # Ensures task is marked as "ok" instead of "changed"

- name: Check if 'haproxy control-plane-3' is already configured
  command: grep '    server control-plane-3 {{ hostvars[groups['k3ssvr'][2]].ansible_host }}:6443 check' /etc/haproxy/haproxy.cfg
  register: haproxy_cpl3_check
  ignore_errors: yes
  changed_when: false  # Ensures task is marked as "ok" instead of "changed"

## Configure haproxy if above conditions are not met
- name: Configure haproxy
  tags: k3s
  copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0440
  when: 
    - haproxy_cpl1_check.rc != 0  # Only execute if grep didn't find a match      
    - haproxy_cpl2_check.rc != 0  # Only execute if grep didn't find a match      
    - haproxy_cpl3_check.rc != 0  # Only execute if grep didn't find a match              

- name: Update haproxy control-plane-1
  tags: k3s
  lineinfile:
    path: /etc/haproxy/haproxy.cfg
    regexp: '^    server control-plane-1'
    line: "    server control-plane-1 {{ hostvars[groups['k3ssvr'][0]].ansible_host }}:6443 check"
  notify: Restart haproxy
  when: haproxy_cpl1_check.rc != 0  # Only execute if grep didn't find a match     

- name: Update haproxy control-plane-2
  tags: k3s
  lineinfile:
    path: /etc/haproxy/haproxy.cfg
    regexp: '^    server control-plane-2'
    line: "    server control-plane-2 {{ hostvars[groups['k3ssvr'][1]].ansible_host }}:6443 check"
  notify: Restart haproxy
  when: haproxy_cpl2_check.rc != 0  # Only execute if grep didn't find a match    

- name: Update haproxy control-plane-3
  tags: k3s
  lineinfile:
    path: /etc/haproxy/haproxy.cfg
    regexp: '^    server control-plane-3'
    line: "    server control-plane-3 {{ hostvars[groups['k3ssvr'][2]].ansible_host }}:6443 check"
  notify: Restart haproxy
  when: haproxy_cpl3_check.rc != 0  # Only execute if grep didn't find a match